#!/bin/bash

# Create the openshift media directory
if [ ! -d $OPENSHIFT_DATA_DIR/media ]; then
	mkdir $OPENSHIFT_DATA_DIR/media
fi

# Symbolically link this to the file running in the openshift gear
ln -sf $OPENSHIFT_DATA_DIR/media $OPENSHIFT_REPO_DIR/wsgi/static/media